// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	UpdateProcessRequest
	UpdateProcessResponse
	CreateContainerRequest
	CreateContainerResponse
	SignalRequest
	SignalResponse
	AddProcessRequest
	Rlimit
	User
	AddProcessResponse
	CreateCheckpointRequest
	CreateCheckpointResponse
	DeleteCheckpointRequest
	DeleteCheckpointResponse
	ListCheckpointRequest
	Checkpoint
	ListCheckpointResponse
	StateRequest
	ContainerState
	Process
	Container
	Machine
	StateResponse
	UpdateContainerRequest
	UpdateResource
	UpdateContainerResponse
	EventsRequest
	Event
	NetworkStats
	CpuUsage
	ThrottlingData
	CpuStats
	PidsStats
	MemoryData
	MemoryStats
	BlkioStatsEntry
	BlkioStats
	HugetlbStats
	CgroupStats
	StatsResponse
	StatsRequest
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type UpdateProcessRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Pid        string `protobuf:"bytes,2,opt,name=pid" json:"pid,omitempty"`
	CloseStdin bool   `protobuf:"varint,3,opt,name=closeStdin" json:"closeStdin,omitempty"`
	Width      uint32 `protobuf:"varint,4,opt,name=width" json:"width,omitempty"`
	Height     uint32 `protobuf:"varint,5,opt,name=height" json:"height,omitempty"`
}

func (m *UpdateProcessRequest) Reset()                    { *m = UpdateProcessRequest{} }
func (m *UpdateProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProcessRequest) ProtoMessage()               {}
func (*UpdateProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UpdateProcessResponse struct {
}

func (m *UpdateProcessResponse) Reset()                    { *m = UpdateProcessResponse{} }
func (m *UpdateProcessResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateProcessResponse) ProtoMessage()               {}
func (*UpdateProcessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateContainerRequest struct {
	Id          string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	BundlePath  string   `protobuf:"bytes,2,opt,name=bundlePath" json:"bundlePath,omitempty"`
	Runtime     string   `protobuf:"bytes,3,opt,name=runtime" json:"runtime,omitempty"`
	Checkpoint  string   `protobuf:"bytes,4,opt,name=checkpoint" json:"checkpoint,omitempty"`
	Stdin       string   `protobuf:"bytes,5,opt,name=stdin" json:"stdin,omitempty"`
	Stdout      string   `protobuf:"bytes,6,opt,name=stdout" json:"stdout,omitempty"`
	Stderr      string   `protobuf:"bytes,7,opt,name=stderr" json:"stderr,omitempty"`
	Labels      []string `protobuf:"bytes,8,rep,name=labels" json:"labels,omitempty"`
	NoPivotRoot bool     `protobuf:"varint,9,opt,name=noPivotRoot" json:"noPivotRoot,omitempty"`
}

func (m *CreateContainerRequest) Reset()                    { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()               {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CreateContainerResponse struct {
	Container *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
}

func (m *CreateContainerResponse) Reset()                    { *m = CreateContainerResponse{} }
func (m *CreateContainerResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateContainerResponse) ProtoMessage()               {}
func (*CreateContainerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateContainerResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type SignalRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Pid    string `protobuf:"bytes,2,opt,name=pid" json:"pid,omitempty"`
	Signal uint32 `protobuf:"varint,3,opt,name=signal" json:"signal,omitempty"`
}

func (m *SignalRequest) Reset()                    { *m = SignalRequest{} }
func (m *SignalRequest) String() string            { return proto.CompactTextString(m) }
func (*SignalRequest) ProtoMessage()               {}
func (*SignalRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SignalResponse struct {
}

func (m *SignalResponse) Reset()                    { *m = SignalResponse{} }
func (m *SignalResponse) String() string            { return proto.CompactTextString(m) }
func (*SignalResponse) ProtoMessage()               {}
func (*SignalResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type AddProcessRequest struct {
	Id              string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Runtime         string    `protobuf:"bytes,2,opt,name=runtime" json:"runtime,omitempty"`
	Terminal        bool      `protobuf:"varint,3,opt,name=terminal" json:"terminal,omitempty"`
	User            *User     `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	Args            []string  `protobuf:"bytes,5,rep,name=args" json:"args,omitempty"`
	Env             []string  `protobuf:"bytes,6,rep,name=env" json:"env,omitempty"`
	Cwd             string    `protobuf:"bytes,7,opt,name=cwd" json:"cwd,omitempty"`
	Pid             string    `protobuf:"bytes,8,opt,name=pid" json:"pid,omitempty"`
	Stdin           string    `protobuf:"bytes,9,opt,name=stdin" json:"stdin,omitempty"`
	Stdout          string    `protobuf:"bytes,10,opt,name=stdout" json:"stdout,omitempty"`
	Stderr          string    `protobuf:"bytes,11,opt,name=stderr" json:"stderr,omitempty"`
	Capabilities    []string  `protobuf:"bytes,12,rep,name=capabilities" json:"capabilities,omitempty"`
	ApparmorProfile string    `protobuf:"bytes,13,opt,name=apparmorProfile" json:"apparmorProfile,omitempty"`
	SelinuxLabel    string    `protobuf:"bytes,14,opt,name=selinuxLabel" json:"selinuxLabel,omitempty"`
	NoNewPrivileges bool      `protobuf:"varint,15,opt,name=noNewPrivileges" json:"noNewPrivileges,omitempty"`
	Rlimits         []*Rlimit `protobuf:"bytes,16,rep,name=rlimits" json:"rlimits,omitempty"`
}

func (m *AddProcessRequest) Reset()                    { *m = AddProcessRequest{} }
func (m *AddProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*AddProcessRequest) ProtoMessage()               {}
func (*AddProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AddProcessRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AddProcessRequest) GetRlimits() []*Rlimit {
	if m != nil {
		return m.Rlimits
	}
	return nil
}

type Rlimit struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Soft uint64 `protobuf:"varint,2,opt,name=soft" json:"soft,omitempty"`
	Hard uint64 `protobuf:"varint,3,opt,name=hard" json:"hard,omitempty"`
}

func (m *Rlimit) Reset()                    { *m = Rlimit{} }
func (m *Rlimit) String() string            { return proto.CompactTextString(m) }
func (*Rlimit) ProtoMessage()               {}
func (*Rlimit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type User struct {
	Uid            uint32   `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Gid            uint32   `protobuf:"varint,2,opt,name=gid" json:"gid,omitempty"`
	AdditionalGids []uint32 `protobuf:"varint,3,rep,name=additionalGids" json:"additionalGids,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type AddProcessResponse struct {
}

func (m *AddProcessResponse) Reset()                    { *m = AddProcessResponse{} }
func (m *AddProcessResponse) String() string            { return proto.CompactTextString(m) }
func (*AddProcessResponse) ProtoMessage()               {}
func (*AddProcessResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type CreateCheckpointRequest struct {
	Id         string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Checkpoint *Checkpoint `protobuf:"bytes,2,opt,name=checkpoint" json:"checkpoint,omitempty"`
}

func (m *CreateCheckpointRequest) Reset()                    { *m = CreateCheckpointRequest{} }
func (m *CreateCheckpointRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCheckpointRequest) ProtoMessage()               {}
func (*CreateCheckpointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateCheckpointRequest) GetCheckpoint() *Checkpoint {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

type CreateCheckpointResponse struct {
}

func (m *CreateCheckpointResponse) Reset()                    { *m = CreateCheckpointResponse{} }
func (m *CreateCheckpointResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCheckpointResponse) ProtoMessage()               {}
func (*CreateCheckpointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type DeleteCheckpointRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteCheckpointRequest) Reset()                    { *m = DeleteCheckpointRequest{} }
func (m *DeleteCheckpointRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCheckpointRequest) ProtoMessage()               {}
func (*DeleteCheckpointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type DeleteCheckpointResponse struct {
}

func (m *DeleteCheckpointResponse) Reset()                    { *m = DeleteCheckpointResponse{} }
func (m *DeleteCheckpointResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCheckpointResponse) ProtoMessage()               {}
func (*DeleteCheckpointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type ListCheckpointRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ListCheckpointRequest) Reset()                    { *m = ListCheckpointRequest{} }
func (m *ListCheckpointRequest) String() string            { return proto.CompactTextString(m) }
func (*ListCheckpointRequest) ProtoMessage()               {}
func (*ListCheckpointRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type Checkpoint struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Exit        bool   `protobuf:"varint,2,opt,name=exit" json:"exit,omitempty"`
	Tcp         bool   `protobuf:"varint,3,opt,name=tcp" json:"tcp,omitempty"`
	UnixSockets bool   `protobuf:"varint,4,opt,name=unixSockets" json:"unixSockets,omitempty"`
	Shell       bool   `protobuf:"varint,5,opt,name=shell" json:"shell,omitempty"`
}

func (m *Checkpoint) Reset()                    { *m = Checkpoint{} }
func (m *Checkpoint) String() string            { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()               {}
func (*Checkpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type ListCheckpointResponse struct {
	Checkpoints []*Checkpoint `protobuf:"bytes,1,rep,name=checkpoints" json:"checkpoints,omitempty"`
}

func (m *ListCheckpointResponse) Reset()                    { *m = ListCheckpointResponse{} }
func (m *ListCheckpointResponse) String() string            { return proto.CompactTextString(m) }
func (*ListCheckpointResponse) ProtoMessage()               {}
func (*ListCheckpointResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ListCheckpointResponse) GetCheckpoints() []*Checkpoint {
	if m != nil {
		return m.Checkpoints
	}
	return nil
}

type StateRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *StateRequest) Reset()                    { *m = StateRequest{} }
func (m *StateRequest) String() string            { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()               {}
func (*StateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type ContainerState struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *ContainerState) Reset()                    { *m = ContainerState{} }
func (m *ContainerState) String() string            { return proto.CompactTextString(m) }
func (*ContainerState) ProtoMessage()               {}
func (*ContainerState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type Process struct {
	Pid             string    `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
	Terminal        bool      `protobuf:"varint,2,opt,name=terminal" json:"terminal,omitempty"`
	User            *User     `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Args            []string  `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	Env             []string  `protobuf:"bytes,5,rep,name=env" json:"env,omitempty"`
	Cwd             string    `protobuf:"bytes,6,opt,name=cwd" json:"cwd,omitempty"`
	SystemPid       uint32    `protobuf:"varint,7,opt,name=systemPid" json:"systemPid,omitempty"`
	Stdin           string    `protobuf:"bytes,8,opt,name=stdin" json:"stdin,omitempty"`
	Stdout          string    `protobuf:"bytes,9,opt,name=stdout" json:"stdout,omitempty"`
	Stderr          string    `protobuf:"bytes,10,opt,name=stderr" json:"stderr,omitempty"`
	Capabilities    []string  `protobuf:"bytes,11,rep,name=capabilities" json:"capabilities,omitempty"`
	ApparmorProfile string    `protobuf:"bytes,12,opt,name=apparmorProfile" json:"apparmorProfile,omitempty"`
	SelinuxLabel    string    `protobuf:"bytes,13,opt,name=selinuxLabel" json:"selinuxLabel,omitempty"`
	NoNewPrivileges bool      `protobuf:"varint,14,opt,name=noNewPrivileges" json:"noNewPrivileges,omitempty"`
	Rlimits         []*Rlimit `protobuf:"bytes,15,rep,name=rlimits" json:"rlimits,omitempty"`
}

func (m *Process) Reset()                    { *m = Process{} }
func (m *Process) String() string            { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()               {}
func (*Process) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Process) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Process) GetRlimits() []*Rlimit {
	if m != nil {
		return m.Rlimits
	}
	return nil
}

type Container struct {
	Id         string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	BundlePath string     `protobuf:"bytes,2,opt,name=bundlePath" json:"bundlePath,omitempty"`
	Processes  []*Process `protobuf:"bytes,3,rep,name=processes" json:"processes,omitempty"`
	Status     string     `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Labels     []string   `protobuf:"bytes,5,rep,name=labels" json:"labels,omitempty"`
	Pids       []uint32   `protobuf:"varint,6,rep,name=pids" json:"pids,omitempty"`
	Runtime    string     `protobuf:"bytes,7,opt,name=runtime" json:"runtime,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Container) GetProcesses() []*Process {
	if m != nil {
		return m.Processes
	}
	return nil
}

// Machine is information about machine on which containerd is run
type Machine struct {
	Cpus   uint32 `protobuf:"varint,1,opt,name=cpus" json:"cpus,omitempty"`
	Memory uint64 `protobuf:"varint,2,opt,name=memory" json:"memory,omitempty"`
}

func (m *Machine) Reset()                    { *m = Machine{} }
func (m *Machine) String() string            { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()               {}
func (*Machine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

// StateResponse is information about containerd daemon
type StateResponse struct {
	Containers []*Container `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	Machine    *Machine     `protobuf:"bytes,2,opt,name=machine" json:"machine,omitempty"`
}

func (m *StateResponse) Reset()                    { *m = StateResponse{} }
func (m *StateResponse) String() string            { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()               {}
func (*StateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *StateResponse) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *StateResponse) GetMachine() *Machine {
	if m != nil {
		return m.Machine
	}
	return nil
}

type UpdateContainerRequest struct {
	Id        string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Pid       string          `protobuf:"bytes,2,opt,name=pid" json:"pid,omitempty"`
	Status    string          `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Resources *UpdateResource `protobuf:"bytes,4,opt,name=resources" json:"resources,omitempty"`
}

func (m *UpdateContainerRequest) Reset()                    { *m = UpdateContainerRequest{} }
func (m *UpdateContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateContainerRequest) ProtoMessage()               {}
func (*UpdateContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *UpdateContainerRequest) GetResources() *UpdateResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type UpdateResource struct {
	BlkioWeight       uint32 `protobuf:"varint,1,opt,name=blkioWeight" json:"blkioWeight,omitempty"`
	CpuShares         uint32 `protobuf:"varint,2,opt,name=cpuShares" json:"cpuShares,omitempty"`
	CpuPeriod         uint32 `protobuf:"varint,3,opt,name=cpuPeriod" json:"cpuPeriod,omitempty"`
	CpuQuota          uint32 `protobuf:"varint,4,opt,name=cpuQuota" json:"cpuQuota,omitempty"`
	CpusetCpus        string `protobuf:"bytes,5,opt,name=cpusetCpus" json:"cpusetCpus,omitempty"`
	CpusetMems        string `protobuf:"bytes,6,opt,name=cpusetMems" json:"cpusetMems,omitempty"`
	MemoryLimit       uint32 `protobuf:"varint,7,opt,name=memoryLimit" json:"memoryLimit,omitempty"`
	MemorySwap        uint32 `protobuf:"varint,8,opt,name=memorySwap" json:"memorySwap,omitempty"`
	MemoryReservation uint32 `protobuf:"varint,9,opt,name=memoryReservation" json:"memoryReservation,omitempty"`
	KernelMemoryLimit uint32 `protobuf:"varint,10,opt,name=kernelMemoryLimit" json:"kernelMemoryLimit,omitempty"`
}

func (m *UpdateResource) Reset()                    { *m = UpdateResource{} }
func (m *UpdateResource) String() string            { return proto.CompactTextString(m) }
func (*UpdateResource) ProtoMessage()               {}
func (*UpdateResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type UpdateContainerResponse struct {
}

func (m *UpdateContainerResponse) Reset()                    { *m = UpdateContainerResponse{} }
func (m *UpdateContainerResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateContainerResponse) ProtoMessage()               {}
func (*UpdateContainerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type EventsRequest struct {
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *EventsRequest) Reset()                    { *m = EventsRequest{} }
func (m *EventsRequest) String() string            { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()               {}
func (*EventsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

type Event struct {
	Type      string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Status    uint32 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Pid       string `protobuf:"bytes,4,opt,name=pid" json:"pid,omitempty"`
	Timestamp uint64 `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type NetworkStats struct {
	Name       string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	RxBytes    uint64 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes" json:"rx_bytes,omitempty"`
	Rx_Packets uint64 `protobuf:"varint,3,opt,name=rx_Packets,json=rxPackets" json:"rx_Packets,omitempty"`
	RxErrors   uint64 `protobuf:"varint,4,opt,name=Rx_errors,json=rxErrors" json:"Rx_errors,omitempty"`
	RxDropped  uint64 `protobuf:"varint,5,opt,name=Rx_dropped,json=rxDropped" json:"Rx_dropped,omitempty"`
	TxBytes    uint64 `protobuf:"varint,6,opt,name=Tx_bytes,json=txBytes" json:"Tx_bytes,omitempty"`
	TxPackets  uint64 `protobuf:"varint,7,opt,name=Tx_packets,json=txPackets" json:"Tx_packets,omitempty"`
	TxErrors   uint64 `protobuf:"varint,8,opt,name=Tx_errors,json=txErrors" json:"Tx_errors,omitempty"`
	TxDropped  uint64 `protobuf:"varint,9,opt,name=Tx_dropped,json=txDropped" json:"Tx_dropped,omitempty"`
}

func (m *NetworkStats) Reset()                    { *m = NetworkStats{} }
func (m *NetworkStats) String() string            { return proto.CompactTextString(m) }
func (*NetworkStats) ProtoMessage()               {}
func (*NetworkStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type CpuUsage struct {
	TotalUsage        uint64   `protobuf:"varint,1,opt,name=total_usage,json=totalUsage" json:"total_usage,omitempty"`
	PercpuUsage       []uint64 `protobuf:"varint,2,rep,name=percpu_usage,json=percpuUsage" json:"percpu_usage,omitempty"`
	UsageInKernelmode uint64   `protobuf:"varint,3,opt,name=usage_in_kernelmode,json=usageInKernelmode" json:"usage_in_kernelmode,omitempty"`
	UsageInUsermode   uint64   `protobuf:"varint,4,opt,name=usage_in_usermode,json=usageInUsermode" json:"usage_in_usermode,omitempty"`
}

func (m *CpuUsage) Reset()                    { *m = CpuUsage{} }
func (m *CpuUsage) String() string            { return proto.CompactTextString(m) }
func (*CpuUsage) ProtoMessage()               {}
func (*CpuUsage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type ThrottlingData struct {
	Periods          uint64 `protobuf:"varint,1,opt,name=periods" json:"periods,omitempty"`
	ThrottledPeriods uint64 `protobuf:"varint,2,opt,name=throttled_periods,json=throttledPeriods" json:"throttled_periods,omitempty"`
	ThrottledTime    uint64 `protobuf:"varint,3,opt,name=throttled_time,json=throttledTime" json:"throttled_time,omitempty"`
}

func (m *ThrottlingData) Reset()                    { *m = ThrottlingData{} }
func (m *ThrottlingData) String() string            { return proto.CompactTextString(m) }
func (*ThrottlingData) ProtoMessage()               {}
func (*ThrottlingData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type CpuStats struct {
	CpuUsage       *CpuUsage       `protobuf:"bytes,1,opt,name=cpu_usage,json=cpuUsage" json:"cpu_usage,omitempty"`
	ThrottlingData *ThrottlingData `protobuf:"bytes,2,opt,name=throttling_data,json=throttlingData" json:"throttling_data,omitempty"`
	SystemUsage    uint64          `protobuf:"varint,3,opt,name=system_usage,json=systemUsage" json:"system_usage,omitempty"`
}

func (m *CpuStats) Reset()                    { *m = CpuStats{} }
func (m *CpuStats) String() string            { return proto.CompactTextString(m) }
func (*CpuStats) ProtoMessage()               {}
func (*CpuStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *CpuStats) GetCpuUsage() *CpuUsage {
	if m != nil {
		return m.CpuUsage
	}
	return nil
}

func (m *CpuStats) GetThrottlingData() *ThrottlingData {
	if m != nil {
		return m.ThrottlingData
	}
	return nil
}

type PidsStats struct {
	Current uint64 `protobuf:"varint,1,opt,name=current" json:"current,omitempty"`
	Limit   uint64 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *PidsStats) Reset()                    { *m = PidsStats{} }
func (m *PidsStats) String() string            { return proto.CompactTextString(m) }
func (*PidsStats) ProtoMessage()               {}
func (*PidsStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type MemoryData struct {
	Usage    uint64 `protobuf:"varint,1,opt,name=usage" json:"usage,omitempty"`
	MaxUsage uint64 `protobuf:"varint,2,opt,name=max_usage,json=maxUsage" json:"max_usage,omitempty"`
	Failcnt  uint64 `protobuf:"varint,3,opt,name=failcnt" json:"failcnt,omitempty"`
	Limit    uint64 `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
}

func (m *MemoryData) Reset()                    { *m = MemoryData{} }
func (m *MemoryData) String() string            { return proto.CompactTextString(m) }
func (*MemoryData) ProtoMessage()               {}
func (*MemoryData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

type MemoryStats struct {
	Cache       uint64            `protobuf:"varint,1,opt,name=cache" json:"cache,omitempty"`
	Usage       *MemoryData       `protobuf:"bytes,2,opt,name=usage" json:"usage,omitempty"`
	SwapUsage   *MemoryData       `protobuf:"bytes,3,opt,name=swap_usage,json=swapUsage" json:"swap_usage,omitempty"`
	KernelUsage *MemoryData       `protobuf:"bytes,4,opt,name=kernel_usage,json=kernelUsage" json:"kernel_usage,omitempty"`
	Stats       map[string]uint64 `protobuf:"bytes,5,rep,name=stats" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *MemoryStats) Reset()                    { *m = MemoryStats{} }
func (m *MemoryStats) String() string            { return proto.CompactTextString(m) }
func (*MemoryStats) ProtoMessage()               {}
func (*MemoryStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *MemoryStats) GetUsage() *MemoryData {
	if m != nil {
		return m.Usage
	}
	return nil
}

func (m *MemoryStats) GetSwapUsage() *MemoryData {
	if m != nil {
		return m.SwapUsage
	}
	return nil
}

func (m *MemoryStats) GetKernelUsage() *MemoryData {
	if m != nil {
		return m.KernelUsage
	}
	return nil
}

func (m *MemoryStats) GetStats() map[string]uint64 {
	if m != nil {
		return m.Stats
	}
	return nil
}

type BlkioStatsEntry struct {
	Major uint64 `protobuf:"varint,1,opt,name=major" json:"major,omitempty"`
	Minor uint64 `protobuf:"varint,2,opt,name=minor" json:"minor,omitempty"`
	Op    string `protobuf:"bytes,3,opt,name=op" json:"op,omitempty"`
	Value uint64 `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
}

func (m *BlkioStatsEntry) Reset()                    { *m = BlkioStatsEntry{} }
func (m *BlkioStatsEntry) String() string            { return proto.CompactTextString(m) }
func (*BlkioStatsEntry) ProtoMessage()               {}
func (*BlkioStatsEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

type BlkioStats struct {
	IoServiceBytesRecursive []*BlkioStatsEntry `protobuf:"bytes,1,rep,name=io_service_bytes_recursive,json=ioServiceBytesRecursive" json:"io_service_bytes_recursive,omitempty"`
	IoServicedRecursive     []*BlkioStatsEntry `protobuf:"bytes,2,rep,name=io_serviced_recursive,json=ioServicedRecursive" json:"io_serviced_recursive,omitempty"`
	IoQueuedRecursive       []*BlkioStatsEntry `protobuf:"bytes,3,rep,name=io_queued_recursive,json=ioQueuedRecursive" json:"io_queued_recursive,omitempty"`
	IoServiceTimeRecursive  []*BlkioStatsEntry `protobuf:"bytes,4,rep,name=io_service_time_recursive,json=ioServiceTimeRecursive" json:"io_service_time_recursive,omitempty"`
	IoWaitTimeRecursive     []*BlkioStatsEntry `protobuf:"bytes,5,rep,name=io_wait_time_recursive,json=ioWaitTimeRecursive" json:"io_wait_time_recursive,omitempty"`
	IoMergedRecursive       []*BlkioStatsEntry `protobuf:"bytes,6,rep,name=io_merged_recursive,json=ioMergedRecursive" json:"io_merged_recursive,omitempty"`
	IoTimeRecursive         []*BlkioStatsEntry `protobuf:"bytes,7,rep,name=io_time_recursive,json=ioTimeRecursive" json:"io_time_recursive,omitempty"`
	SectorsRecursive        []*BlkioStatsEntry `protobuf:"bytes,8,rep,name=sectors_recursive,json=sectorsRecursive" json:"sectors_recursive,omitempty"`
}

func (m *BlkioStats) Reset()                    { *m = BlkioStats{} }
func (m *BlkioStats) String() string            { return proto.CompactTextString(m) }
func (*BlkioStats) ProtoMessage()               {}
func (*BlkioStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *BlkioStats) GetIoServiceBytesRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoServiceBytesRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoServicedRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoServicedRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoQueuedRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoQueuedRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoServiceTimeRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoServiceTimeRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoWaitTimeRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoWaitTimeRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoMergedRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoMergedRecursive
	}
	return nil
}

func (m *BlkioStats) GetIoTimeRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.IoTimeRecursive
	}
	return nil
}

func (m *BlkioStats) GetSectorsRecursive() []*BlkioStatsEntry {
	if m != nil {
		return m.SectorsRecursive
	}
	return nil
}

type HugetlbStats struct {
	Usage    uint64 `protobuf:"varint,1,opt,name=usage" json:"usage,omitempty"`
	MaxUsage uint64 `protobuf:"varint,2,opt,name=max_usage,json=maxUsage" json:"max_usage,omitempty"`
	Failcnt  uint64 `protobuf:"varint,3,opt,name=failcnt" json:"failcnt,omitempty"`
	Limit    uint64 `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
}

func (m *HugetlbStats) Reset()                    { *m = HugetlbStats{} }
func (m *HugetlbStats) String() string            { return proto.CompactTextString(m) }
func (*HugetlbStats) ProtoMessage()               {}
func (*HugetlbStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

type CgroupStats struct {
	CpuStats     *CpuStats                `protobuf:"bytes,1,opt,name=cpu_stats,json=cpuStats" json:"cpu_stats,omitempty"`
	MemoryStats  *MemoryStats             `protobuf:"bytes,2,opt,name=memory_stats,json=memoryStats" json:"memory_stats,omitempty"`
	BlkioStats   *BlkioStats              `protobuf:"bytes,3,opt,name=blkio_stats,json=blkioStats" json:"blkio_stats,omitempty"`
	HugetlbStats map[string]*HugetlbStats `protobuf:"bytes,4,rep,name=hugetlb_stats,json=hugetlbStats" json:"hugetlb_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PidsStats    *PidsStats               `protobuf:"bytes,5,opt,name=pids_stats,json=pidsStats" json:"pids_stats,omitempty"`
}

func (m *CgroupStats) Reset()                    { *m = CgroupStats{} }
func (m *CgroupStats) String() string            { return proto.CompactTextString(m) }
func (*CgroupStats) ProtoMessage()               {}
func (*CgroupStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *CgroupStats) GetCpuStats() *CpuStats {
	if m != nil {
		return m.CpuStats
	}
	return nil
}

func (m *CgroupStats) GetMemoryStats() *MemoryStats {
	if m != nil {
		return m.MemoryStats
	}
	return nil
}

func (m *CgroupStats) GetBlkioStats() *BlkioStats {
	if m != nil {
		return m.BlkioStats
	}
	return nil
}

func (m *CgroupStats) GetHugetlbStats() map[string]*HugetlbStats {
	if m != nil {
		return m.HugetlbStats
	}
	return nil
}

func (m *CgroupStats) GetPidsStats() *PidsStats {
	if m != nil {
		return m.PidsStats
	}
	return nil
}

type StatsResponse struct {
	NetworkStats []*NetworkStats `protobuf:"bytes,1,rep,name=network_stats,json=networkStats" json:"network_stats,omitempty"`
	CgroupStats  *CgroupStats    `protobuf:"bytes,2,opt,name=cgroup_stats,json=cgroupStats" json:"cgroup_stats,omitempty"`
	Timestamp    uint64          `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *StatsResponse) Reset()                    { *m = StatsResponse{} }
func (m *StatsResponse) String() string            { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()               {}
func (*StatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *StatsResponse) GetNetworkStats() []*NetworkStats {
	if m != nil {
		return m.NetworkStats
	}
	return nil
}

func (m *StatsResponse) GetCgroupStats() *CgroupStats {
	if m != nil {
		return m.CgroupStats
	}
	return nil
}

type StatsRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *StatsRequest) Reset()                    { *m = StatsRequest{} }
func (m *StatsRequest) String() string            { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()               {}
func (*StatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func init() {
	proto.RegisterType((*UpdateProcessRequest)(nil), "types.UpdateProcessRequest")
	proto.RegisterType((*UpdateProcessResponse)(nil), "types.UpdateProcessResponse")
	proto.RegisterType((*CreateContainerRequest)(nil), "types.CreateContainerRequest")
	proto.RegisterType((*CreateContainerResponse)(nil), "types.CreateContainerResponse")
	proto.RegisterType((*SignalRequest)(nil), "types.SignalRequest")
	proto.RegisterType((*SignalResponse)(nil), "types.SignalResponse")
	proto.RegisterType((*AddProcessRequest)(nil), "types.AddProcessRequest")
	proto.RegisterType((*Rlimit)(nil), "types.Rlimit")
	proto.RegisterType((*User)(nil), "types.User")
	proto.RegisterType((*AddProcessResponse)(nil), "types.AddProcessResponse")
	proto.RegisterType((*CreateCheckpointRequest)(nil), "types.CreateCheckpointRequest")
	proto.RegisterType((*CreateCheckpointResponse)(nil), "types.CreateCheckpointResponse")
	proto.RegisterType((*DeleteCheckpointRequest)(nil), "types.DeleteCheckpointRequest")
	proto.RegisterType((*DeleteCheckpointResponse)(nil), "types.DeleteCheckpointResponse")
	proto.RegisterType((*ListCheckpointRequest)(nil), "types.ListCheckpointRequest")
	proto.RegisterType((*Checkpoint)(nil), "types.Checkpoint")
	proto.RegisterType((*ListCheckpointResponse)(nil), "types.ListCheckpointResponse")
	proto.RegisterType((*StateRequest)(nil), "types.StateRequest")
	proto.RegisterType((*ContainerState)(nil), "types.ContainerState")
	proto.RegisterType((*Process)(nil), "types.Process")
	proto.RegisterType((*Container)(nil), "types.Container")
	proto.RegisterType((*Machine)(nil), "types.Machine")
	proto.RegisterType((*StateResponse)(nil), "types.StateResponse")
	proto.RegisterType((*UpdateContainerRequest)(nil), "types.UpdateContainerRequest")
	proto.RegisterType((*UpdateResource)(nil), "types.UpdateResource")
	proto.RegisterType((*UpdateContainerResponse)(nil), "types.UpdateContainerResponse")
	proto.RegisterType((*EventsRequest)(nil), "types.EventsRequest")
	proto.RegisterType((*Event)(nil), "types.Event")
	proto.RegisterType((*NetworkStats)(nil), "types.NetworkStats")
	proto.RegisterType((*CpuUsage)(nil), "types.CpuUsage")
	proto.RegisterType((*ThrottlingData)(nil), "types.ThrottlingData")
	proto.RegisterType((*CpuStats)(nil), "types.CpuStats")
	proto.RegisterType((*PidsStats)(nil), "types.PidsStats")
	proto.RegisterType((*MemoryData)(nil), "types.MemoryData")
	proto.RegisterType((*MemoryStats)(nil), "types.MemoryStats")
	proto.RegisterType((*BlkioStatsEntry)(nil), "types.BlkioStatsEntry")
	proto.RegisterType((*BlkioStats)(nil), "types.BlkioStats")
	proto.RegisterType((*HugetlbStats)(nil), "types.HugetlbStats")
	proto.RegisterType((*CgroupStats)(nil), "types.CgroupStats")
	proto.RegisterType((*StatsResponse)(nil), "types.StatsResponse")
	proto.RegisterType((*StatsRequest)(nil), "types.StatsRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
//const _ = grpc.SupportPackageIsVersion1

// Client API for API service

type APIClient interface {
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error)
	UpdateContainer(ctx context.Context, in *UpdateContainerRequest, opts ...grpc.CallOption) (*UpdateContainerResponse, error)
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	UpdateProcess(ctx context.Context, in *UpdateProcessRequest, opts ...grpc.CallOption) (*UpdateProcessResponse, error)
	AddProcess(ctx context.Context, in *AddProcessRequest, opts ...grpc.CallOption) (*AddProcessResponse, error)
	CreateCheckpoint(ctx context.Context, in *CreateCheckpointRequest, opts ...grpc.CallOption) (*CreateCheckpointResponse, error)
	DeleteCheckpoint(ctx context.Context, in *DeleteCheckpointRequest, opts ...grpc.CallOption) (*DeleteCheckpointResponse, error)
	ListCheckpoint(ctx context.Context, in *ListCheckpointRequest, opts ...grpc.CallOption) (*ListCheckpointResponse, error)
	State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (API_EventsClient, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerResponse, error) {
	out := new(CreateContainerResponse)
	err := grpc.Invoke(ctx, "/types.API/CreateContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateContainer(ctx context.Context, in *UpdateContainerRequest, opts ...grpc.CallOption) (*UpdateContainerResponse, error) {
	out := new(UpdateContainerResponse)
	err := grpc.Invoke(ctx, "/types.API/UpdateContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	out := new(SignalResponse)
	err := grpc.Invoke(ctx, "/types.API/Signal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateProcess(ctx context.Context, in *UpdateProcessRequest, opts ...grpc.CallOption) (*UpdateProcessResponse, error) {
	out := new(UpdateProcessResponse)
	err := grpc.Invoke(ctx, "/types.API/UpdateProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AddProcess(ctx context.Context, in *AddProcessRequest, opts ...grpc.CallOption) (*AddProcessResponse, error) {
	out := new(AddProcessResponse)
	err := grpc.Invoke(ctx, "/types.API/AddProcess", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateCheckpoint(ctx context.Context, in *CreateCheckpointRequest, opts ...grpc.CallOption) (*CreateCheckpointResponse, error) {
	out := new(CreateCheckpointResponse)
	err := grpc.Invoke(ctx, "/types.API/CreateCheckpoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteCheckpoint(ctx context.Context, in *DeleteCheckpointRequest, opts ...grpc.CallOption) (*DeleteCheckpointResponse, error) {
	out := new(DeleteCheckpointResponse)
	err := grpc.Invoke(ctx, "/types.API/DeleteCheckpoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListCheckpoint(ctx context.Context, in *ListCheckpointRequest, opts ...grpc.CallOption) (*ListCheckpointResponse, error) {
	out := new(ListCheckpointResponse)
	err := grpc.Invoke(ctx, "/types.API/ListCheckpoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	out := new(StateResponse)
	err := grpc.Invoke(ctx, "/types.API/State", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (API_EventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_API_serviceDesc.Streams[0], c.cc, "/types.API/Events", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_EventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type aPIEventsClient struct {
	grpc.ClientStream
}

func (x *aPIEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := grpc.Invoke(ctx, "/types.API/Stats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerResponse, error)
	UpdateContainer(context.Context, *UpdateContainerRequest) (*UpdateContainerResponse, error)
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	UpdateProcess(context.Context, *UpdateProcessRequest) (*UpdateProcessResponse, error)
	AddProcess(context.Context, *AddProcessRequest) (*AddProcessResponse, error)
	CreateCheckpoint(context.Context, *CreateCheckpointRequest) (*CreateCheckpointResponse, error)
	DeleteCheckpoint(context.Context, *DeleteCheckpointRequest) (*DeleteCheckpointResponse, error)
	ListCheckpoint(context.Context, *ListCheckpointRequest) (*ListCheckpointResponse, error)
	State(context.Context, *StateRequest) (*StateResponse, error)
	Events(*EventsRequest, API_EventsServer) error
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).CreateContainer(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_UpdateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UpdateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).UpdateContainer(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).Signal(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_UpdateProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UpdateProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).UpdateProcess(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_AddProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AddProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).AddProcess(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_CreateCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreateCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).CreateCheckpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_DeleteCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DeleteCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).DeleteCheckpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_ListCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).ListCheckpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).State(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).Events(m, &aPIEventsServer{stream})
}

type API_EventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type aPIEventsServer struct {
	grpc.ServerStream
}

func (x *aPIEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _API_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).Stats(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _API_CreateContainer_Handler,
		},
		{
			MethodName: "UpdateContainer",
			Handler:    _API_UpdateContainer_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _API_Signal_Handler,
		},
		{
			MethodName: "UpdateProcess",
			Handler:    _API_UpdateProcess_Handler,
		},
		{
			MethodName: "AddProcess",
			Handler:    _API_AddProcess_Handler,
		},
		{
			MethodName: "CreateCheckpoint",
			Handler:    _API_CreateCheckpoint_Handler,
		},
		{
			MethodName: "DeleteCheckpoint",
			Handler:    _API_DeleteCheckpoint_Handler,
		},
		{
			MethodName: "ListCheckpoint",
			Handler:    _API_ListCheckpoint_Handler,
		},
		{
			MethodName: "State",
			Handler:    _API_State_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _API_Stats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _API_Events_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 2265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x59, 0x4b, 0x73, 0x23, 0x49,
	0x11, 0x1e, 0x49, 0x2d, 0x59, 0x4a, 0x3d, 0x6c, 0xf7, 0xf8, 0xa1, 0xd1, 0xee, 0xcc, 0x0e, 0x1d,
	0xc0, 0x0e, 0xb0, 0x98, 0xc1, 0xb3, 0x1b, 0x4c, 0x40, 0x40, 0xc4, 0x8e, 0x67, 0x80, 0x61, 0xc7,
	0x8b, 0xa7, 0x6d, 0xc7, 0x5e, 0x88, 0x50, 0xb4, 0xa5, 0x1a, 0xa9, 0xb1, 0xd4, 0xdd, 0xd3, 0xdd,
	0xf2, 0xe3, 0xc2, 0x81, 0x03, 0xdc, 0x38, 0x72, 0x21, 0x82, 0x0b, 0x37, 0xfe, 0x01, 0xbf, 0x80,
	0x23, 0xff, 0x82, 0xe0, 0x27, 0x70, 0x24, 0xab, 0xb2, 0x5e, 0xad, 0x87, 0x6d, 0x0e, 0x7b, 0x51,
	0x54, 0x66, 0x65, 0x65, 0x56, 0xe5, 0xe3, 0xcb, 0xea, 0x12, 0x34, 0x82, 0x24, 0xdc, 0x4b, 0xd2,
	0x38, 0x8f, 0xdd, 0x6a, 0x7e, 0x9d, 0xb0, 0xcc, 0xfb, 0x43, 0x09, 0xb6, 0x4e, 0x93, 0x61, 0x90,
	0xb3, 0xa3, 0x34, 0x1e, 0xb0, 0x2c, 0xf3, 0xd9, 0xfb, 0x19, 0xcb, 0x72, 0xb7, 0x03, 0xe5, 0x70,
	0xd8, 0x2d, 0x3d, 0x2e, 0x3d, 0x69, 0xf8, 0x38, 0x72, 0x37, 0xa0, 0x92, 0x20, 0xa3, 0x2c, 0x18,
	0x7c, 0xe8, 0x3e, 0x02, 0x18, 0x4c, 0xe2, 0x8c, 0x1d, 0xe7, 0xc3, 0x30, 0xea, 0x56, 0x70, 0xa2,
	0xee, 0x5b, 0x1c, 0x77, 0x0b, 0xaa, 0x97, 0xe1, 0x30, 0x1f, 0x77, 0x1d, 0x9c, 0x6a, 0xfb, 0x44,
	0xb8, 0x3b, 0x50, 0x1b, 0xb3, 0x70, 0x34, 0xce, 0xbb, 0x55, 0xc1, 0x96, 0x94, 0xb7, 0x0b, 0xdb,
	0x73, 0xfb, 0xc8, 0x92, 0x38, 0xca, 0x98, 0xf7, 0xfb, 0x32, 0xec, 0x1c, 0xa4, 0x0c, 0x67, 0x0e,
	0xe2, 0x28, 0x0f, 0xc2, 0x88, 0xa5, 0xab, 0xf6, 0x88, 0x3b, 0x3a, 0x9b, 0x45, 0xc3, 0x09, 0x3b,
	0x0a, 0xd0, 0x2c, 0x6d, 0xd5, 0xe2, 0xb8, 0x5d, 0x58, 0x4b, 0x67, 0x51, 0x1e, 0x4e, 0x99, 0xd8,
	0x6e, 0xc3, 0x57, 0xa4, 0x38, 0xcb, 0x98, 0x0d, 0xce, 0x93, 0x38, 0x8c, 0x72, 0xb1, 0x61, 0x5c,
	0x69, 0x38, 0xfc, 0x2c, 0x99, 0x38, 0x66, 0x55, 0x4c, 0x11, 0xc1, 0xcf, 0x82, 0x83, 0x78, 0x96,
	0x77, 0x6b, 0x82, 0x2d, 0x29, 0xc9, 0x67, 0x69, 0xda, 0x5d, 0xd3, 0x7c, 0xa4, 0x38, 0x7f, 0x12,
	0x9c, 0xb1, 0x49, 0xd6, 0xad, 0x3f, 0xae, 0x70, 0x3e, 0x51, 0xee, 0x63, 0x68, 0x46, 0xf1, 0x51,
	0x78, 0x11, 0xe7, 0x7e, 0x1c, 0xe7, 0xdd, 0x86, 0x70, 0xa5, 0xcd, 0xf2, 0x5e, 0xc3, 0xee, 0x82,
	0x0f, 0xc8, 0x3f, 0xee, 0x1e, 0x34, 0x06, 0x8a, 0x29, 0x7c, 0xd1, 0xdc, 0xdf, 0xd8, 0x13, 0xc1,
	0xdd, 0x33, 0xc2, 0x46, 0x04, 0x55, 0xb5, 0x8f, 0xc3, 0x51, 0x14, 0x4c, 0xee, 0x1e, 0x69, 0x7e,
	0x1e, 0xb1, 0x44, 0xb8, 0x0d, 0x63, 0x46, 0x94, 0xb7, 0x01, 0x1d, 0xa5, 0x4a, 0x06, 0xeb, 0x5f,
	0x15, 0xd8, 0xfc, 0x7c, 0x38, 0xbc, 0x25, 0x97, 0xac, 0x38, 0x94, 0x8b, 0x71, 0xe8, 0x41, 0x3d,
	0x67, 0xe9, 0x34, 0x54, 0xb6, 0xea, 0xbe, 0xa6, 0xdd, 0x8f, 0xc0, 0x99, 0x65, 0x78, 0x46, 0x47,
	0x9c, 0xb1, 0x29, 0xcf, 0x78, 0x8a, 0x2c, 0x5f, 0x4c, 0xb8, 0x2e, 0x38, 0x41, 0x3a, 0xca, 0x30,
	0x46, 0xdc, 0xb9, 0x62, 0xcc, 0x0f, 0xc3, 0xa2, 0x0b, 0x8c, 0x0f, 0x67, 0xf1, 0x21, 0xe7, 0x0c,
	0x2e, 0x87, 0x32, 0x32, 0x7c, 0xa8, 0x0e, 0x5c, 0x37, 0x07, 0xd6, 0xe1, 0x6e, 0x2c, 0x0f, 0x37,
	0xac, 0x08, 0x77, 0xb3, 0x10, 0x6e, 0x0f, 0x5a, 0x83, 0x20, 0x09, 0xce, 0xc2, 0x49, 0x98, 0x87,
	0x2c, 0xeb, 0xb6, 0xc4, 0x26, 0x0a, 0x3c, 0xf7, 0x09, 0xac, 0x07, 0x49, 0x12, 0xa4, 0xd3, 0x38,
	0x45, 0xa7, 0xbd, 0x0b, 0x27, 0xac, 0xdb, 0x16, 0x4a, 0xe6, 0xd9, 0x5c, 0x5b, 0xc6, 0x26, 0x61,
	0x34, 0xbb, 0x7a, 0xc3, 0xb3, 0xa6, 0xdb, 0x11, 0x62, 0x05, 0x1e, 0xd7, 0x16, 0xc5, 0x5f, 0xb2,
	0xcb, 0xa3, 0x34, 0xbc, 0xc0, 0x35, 0x23, 0x34, 0xba, 0x2e, 0xbc, 0x38, 0xcf, 0x76, 0x3f, 0xc6,
	0x10, 0x4c, 0xc2, 0x69, 0x98, 0x67, 0xdd, 0x0d, 0xdc, 0x56, 0x73, 0xbf, 0x2d, 0xfd, 0xe9, 0x0b,
	0xae, 0xaf, 0x66, 0xbd, 0x97, 0x50, 0x23, 0x16, 0x77, 0x2f, 0x17, 0x91, 0x71, 0x14, 0x63, 0xce,
	0xcb, 0xe2, 0x77, 0xb9, 0x08, 0xa3, 0xe3, 0x8b, 0x31, 0xe7, 0x8d, 0x83, 0x74, 0x28, 0xe2, 0x87,
	0x3c, 0x3e, 0xf6, 0x7c, 0x70, 0x78, 0xa0, 0xb8, 0xab, 0x67, 0x32, 0x15, 0xda, 0x3e, 0x1f, 0x72,
	0xce, 0x48, 0x66, 0x1b, 0x72, 0x70, 0xe8, 0x7e, 0x1b, 0x3a, 0xc1, 0x70, 0x88, 0xee, 0x89, 0x31,
	0xea, 0xbf, 0x08, 0x87, 0x19, 0x6a, 0xaa, 0xe0, 0xe4, 0x1c, 0xd7, 0xdb, 0x02, 0xd7, 0x4e, 0x35,
	0x99, 0x81, 0xbf, 0xd1, 0x95, 0xa2, 0xab, 0x77, 0x55, 0x1a, 0xfe, 0xb0, 0x50, 0xf4, 0x65, 0x91,
	0x56, 0x9b, 0xaa, 0x74, 0xcc, 0x6a, 0x4b, 0xc8, 0xeb, 0x41, 0x77, 0x51, 0xbb, 0xb4, 0xfc, 0x53,
	0xd8, 0x7d, 0xc9, 0x26, 0xec, 0x2e, 0x96, 0xd1, 0x45, 0x51, 0xa0, 0xb3, 0x5f, 0x8c, 0xb9, 0xea,
	0xc5, 0xe5, 0x52, 0xf5, 0xc7, 0xb0, 0xfd, 0x26, 0xcc, 0xf2, 0x5b, 0x15, 0x7b, 0xbf, 0x03, 0x30,
	0x42, 0xda, 0x4c, 0xc9, 0x98, 0xe1, 0x3c, 0x76, 0x15, 0xd2, 0x71, 0xeb, 0xbe, 0x18, 0xf3, 0x18,
	0xe4, 0x83, 0x44, 0x16, 0x1c, 0x1f, 0x72, 0x44, 0x9a, 0x45, 0xe1, 0xd5, 0x71, 0x3c, 0x38, 0x67,
	0x98, 0x22, 0x0e, 0x21, 0x92, 0xc5, 0x12, 0x25, 0x32, 0x66, 0x93, 0x89, 0x40, 0xc4, 0xba, 0x4f,
	0x84, 0x77, 0x08, 0x3b, 0xf3, 0x1b, 0x95, 0x30, 0xf5, 0x0c, 0x9a, 0xc6, 0x8f, 0x19, 0x6e, 0xa9,
	0xb2, 0xdc, 0xdb, 0xb6, 0x94, 0xf7, 0x08, 0x5a, 0xc7, 0x39, 0x7a, 0x7b, 0xd5, 0x71, 0x9f, 0x40,
	0x47, 0x63, 0x9c, 0x10, 0xa4, 0x5a, 0x0c, 0xf2, 0x59, 0x26, 0xa5, 0x24, 0xe5, 0xfd, 0xa3, 0x02,
	0x6b, 0x32, 0x55, 0x54, 0xbd, 0x97, 0x4c, 0xbd, 0xdb, 0xb0, 0x53, 0x5e, 0x01, 0x3b, 0x95, 0xdb,
	0x60, 0xc7, 0x59, 0x84, 0x9d, 0xea, 0x02, 0xec, 0xd4, 0x0c, 0xec, 0x7c, 0x08, 0x8d, 0xec, 0x3a,
	0xcb, 0xd9, 0xf4, 0x28, 0x24, 0x38, 0x6a, 0xfb, 0x86, 0x61, 0x20, 0xa8, 0xbe, 0x1c, 0x82, 0x1a,
	0x2b, 0x20, 0x08, 0x6e, 0x84, 0xa0, 0xe6, 0xdd, 0x20, 0xa8, 0x75, 0x37, 0x08, 0x6a, 0xdf, 0x0d,
	0x82, 0x3a, 0xb7, 0x42, 0xd0, 0xfa, 0x8d, 0x10, 0xf4, 0xcf, 0x12, 0x34, 0x74, 0x98, 0xff, 0xef,
	0xa6, 0xff, 0x09, 0x34, 0x12, 0x0a, 0x3c, 0x23, 0x24, 0x69, 0xee, 0x77, 0xa4, 0x21, 0x85, 0x1d,
	0x46, 0xc0, 0xca, 0x1f, 0xc7, 0xce, 0x1f, 0xab, 0x75, 0x57, 0x0b, 0xad, 0x1b, 0x83, 0x9f, 0x70,
	0x88, 0xaa, 0x09, 0x88, 0x12, 0x63, 0xbb, 0xbd, 0xad, 0x15, 0xda, 0x9b, 0xf7, 0x19, 0xac, 0x1d,
	0x06, 0x83, 0x31, 0x9e, 0x83, 0x2f, 0x1c, 0x24, 0x32, 0x4d, 0x71, 0x21, 0x1f, 0x73, 0x23, 0x53,
	0x86, 0xfe, 0xbe, 0x96, 0x78, 0x2a, 0x29, 0xef, 0x1c, 0x5b, 0x36, 0x95, 0x81, 0x2c, 0xa6, 0xa7,
	0x88, 0x5c, 0xca, 0x21, 0xaa, 0x96, 0x16, 0x9b, 0xbe, 0x25, 0x83, 0x61, 0x59, 0x9b, 0x92, 0x65,
	0x09, 0x74, 0xca, 0x07, 0x72, 0x3f, 0xbe, 0x9a, 0xf6, 0xfe, 0x58, 0x82, 0x1d, 0xba, 0x89, 0xdd,
	0x7a, 0xdf, 0x5a, 0x7e, 0x53, 0x20, 0xf7, 0x55, 0x0a, 0xee, 0x7b, 0x06, 0x8d, 0x94, 0x65, 0xf1,
	0x2c, 0x45, 0x37, 0xcb, 0x06, 0xbe, 0xad, 0x2a, 0x49, 0xd8, 0xf2, 0xe5, 0xac, 0x6f, 0xe4, 0xbc,
	0xff, 0x94, 0xa1, 0x53, 0x9c, 0xe5, 0xb8, 0x74, 0x36, 0x39, 0x0f, 0xe3, 0xaf, 0xe8, 0x0a, 0x49,
	0xce, 0xb3, 0x59, 0xbc, 0xaa, 0xd0, 0x97, 0xc7, 0xd8, 0x75, 0xd0, 0x12, 0x75, 0x15, 0xc3, 0x90,
	0xb3, 0x47, 0x2c, 0x0d, 0xe3, 0xa1, 0xbc, 0xcc, 0x18, 0x06, 0x87, 0x01, 0x24, 0xde, 0xce, 0xe2,
	0x3c, 0x90, 0x97, 0x56, 0x4d, 0x8b, 0x1b, 0x22, 0xc6, 0x88, 0xe5, 0x07, 0x3c, 0x6a, 0x55, 0x79,
	0x43, 0xd4, 0x1c, 0x33, 0x7f, 0xc8, 0xa6, 0x99, 0x2c, 0x73, 0x8b, 0xc3, 0x77, 0x4e, 0xd1, 0x7c,
	0xc3, 0x93, 0x5a, 0xd6, 0xbb, 0xcd, 0xe2, 0x1a, 0x88, 0x3c, 0xbe, 0x0c, 0x12, 0x51, 0xf6, 0x6d,
	0xdf, 0xe2, 0x60, 0x22, 0x6f, 0x12, 0x85, 0xde, 0x60, 0xe9, 0x45, 0xc0, 0x5b, 0xa1, 0x80, 0x81,
	0xb6, 0xbf, 0x38, 0xc1, 0xa5, 0xcf, 0x59, 0x1a, 0xb1, 0xc9, 0xa1, 0x65, 0x15, 0x48, 0x7a, 0x61,
	0xc2, 0x7b, 0x00, 0xbb, 0x0b, 0x31, 0x97, 0xbd, 0xe7, 0xfb, 0xd0, 0x7e, 0x75, 0xc1, 0x10, 0x8d,
	0x55, 0x16, 0xa0, 0x0f, 0x79, 0x32, 0x63, 0x64, 0xa7, 0x89, 0x88, 0x80, 0xe3, 0x1b, 0x86, 0x97,
	0x41, 0x55, 0x88, 0x2f, 0xbd, 0x2e, 0x50, 0x02, 0x95, 0x75, 0x02, 0x15, 0xd3, 0xa5, 0xad, 0xd3,
	0x45, 0x26, 0x96, 0x63, 0x12, 0xab, 0x60, 0xb4, 0x3a, 0x6f, 0xf4, 0x4f, 0x65, 0x68, 0x7d, 0xc9,
	0xf2, 0xcb, 0x38, 0x3d, 0xe7, 0x85, 0x92, 0x2d, 0xed, 0x7c, 0x0f, 0xa0, 0x9e, 0x5e, 0xf5, 0xcf,
	0xae, 0x73, 0x99, 0x18, 0x0e, 0xd6, 0xe5, 0xd5, 0x0b, 0x4e, 0xba, 0x0f, 0x01, 0x70, 0xea, 0x28,
	0xa0, 0x6e, 0x47, 0x17, 0x97, 0x46, 0x7a, 0x25, 0x19, 0xee, 0x07, 0xd0, 0xf0, 0xaf, 0xfa, 0x88,
	0xa7, 0x71, 0x4a, 0xd9, 0xeb, 0xf8, 0xa8, 0xea, 0x95, 0xa0, 0xf9, 0x5a, 0x9c, 0x1c, 0xa6, 0x71,
	0x92, 0xb0, 0xa1, 0xda, 0x5a, 0x7a, 0xf5, 0x92, 0x18, 0xdc, 0xea, 0x89, 0xb2, 0x5a, 0x23, 0xab,
	0xb9, 0xb1, 0x8a, 0x53, 0x89, 0xb4, 0xba, 0x26, 0x0f, 0x65, 0x5b, 0x3d, 0xd1, 0x56, 0xeb, 0x64,
	0x35, 0xb7, 0xac, 0x9e, 0x18, 0xab, 0x0d, 0xb5, 0x56, 0x5a, 0xf5, 0xfe, 0x5e, 0x82, 0x3a, 0xa6,
	0xe5, 0x69, 0x16, 0x8c, 0x18, 0x76, 0xb0, 0x66, 0x8e, 0x29, 0x3c, 0xe9, 0xcf, 0x38, 0x29, 0x43,
	0x06, 0x82, 0x45, 0x02, 0xdf, 0x80, 0x56, 0xc2, 0x52, 0x4c, 0x56, 0x29, 0x51, 0x46, 0x40, 0x71,
	0xfc, 0x26, 0xf1, 0x48, 0x64, 0x0f, 0xee, 0x8b, 0xb9, 0x7e, 0x18, 0xf5, 0x29, 0x7d, 0xa6, 0xf1,
	0x90, 0x49, 0x57, 0x6d, 0x8a, 0xa9, 0xd7, 0xd1, 0x17, 0x7a, 0xc2, 0xfd, 0x2e, 0x6c, 0x6a, 0x79,
	0xde, 0x25, 0x85, 0x34, 0xb9, 0x6e, 0x5d, 0x4a, 0x9f, 0x4a, 0x36, 0x5e, 0x5a, 0x3a, 0x27, 0x63,
	0xfc, 0x28, 0xcd, 0xb1, 0x8d, 0x8c, 0x5e, 0x06, 0x58, 0x6c, 0x88, 0xa0, 0x89, 0x28, 0xc9, 0x4c,
	0xee, 0x56, 0x91, 0xee, 0xf7, 0x60, 0x33, 0x27, 0x59, 0x36, 0xec, 0x2b, 0x19, 0x8a, 0xe6, 0x86,
	0x9e, 0x38, 0x92, 0xc2, 0xdf, 0x82, 0x8e, 0x11, 0xd6, 0x9f, 0x7d, 0x8e, 0xdf, 0xd6, 0xdc, 0x13,
	0x8e, 0xca, 0x7f, 0x21, 0x67, 0x51, 0xe6, 0x7c, 0x22, 0x10, 0xc2, 0x72, 0x55, 0x73, 0x7f, 0x5d,
	0x21, 0xab, 0x74, 0x86, 0x40, 0x05, 0x72, 0xcb, 0xcf, 0x60, 0x3d, 0xd7, 0x5b, 0xef, 0x63, 0x01,
	0x05, 0x12, 0x5e, 0x15, 0xba, 0x15, 0x0f, 0xe6, 0x77, 0xf2, 0xe2, 0x41, 0xd1, 0xf3, 0xd4, 0xf2,
	0xa5, 0x41, 0xda, 0x5f, 0x93, 0x78, 0xc2, 0x84, 0xf7, 0x13, 0x68, 0xe0, 0x7d, 0x20, 0xa3, 0xdd,
	0xa1, 0x63, 0x06, 0xb3, 0x34, 0xc5, 0xfa, 0x52, 0x8e, 0x91, 0x24, 0xbf, 0x2f, 0x88, 0x76, 0x29,
	0x9d, 0x41, 0x84, 0x17, 0x03, 0x50, 0x99, 0x0b, 0x6b, 0x28, 0x63, 0xa7, 0x00, 0x11, 0x3c, 0xcf,
	0xa6, 0xc1, 0x95, 0x0e, 0xbd, 0xc8, 0x33, 0x64, 0xd0, 0x01, 0xd1, 0xe0, 0xbb, 0x20, 0x9c, 0x0c,
	0xd0, 0x20, 0xed, 0x4d, 0x91, 0xc6, 0xa0, 0x63, 0x1b, 0xfc, 0x5b, 0x19, 0x9a, 0x64, 0x91, 0x36,
	0x8c, 0x52, 0x03, 0x6c, 0x2c, 0xda, 0xa4, 0x20, 0xb0, 0xf5, 0x57, 0x8d, 0x39, 0x73, 0x0d, 0x34,
	0x5b, 0x55, 0x7b, 0xc3, 0x46, 0x97, 0x21, 0xf6, 0x59, 0xde, 0x59, 0x2a, 0xdd, 0xe0, 0x42, 0xb4,
	0xe1, 0x4f, 0xa1, 0x45, 0xf9, 0x29, 0xd7, 0x38, 0xab, 0xd6, 0x34, 0x49, 0x8c, 0x56, 0x3d, 0xe3,
	0xb7, 0x2d, 0xdc, 0xaf, 0xe8, 0xee, 0xcd, 0xfd, 0x87, 0x05, 0x71, 0x71, 0x92, 0x3d, 0xf1, 0xfb,
	0x2a, 0xca, 0x11, 0x66, 0x49, 0xb6, 0xf7, 0x1c, 0xc0, 0x30, 0x39, 0x66, 0x9d, 0xb3, 0x6b, 0x75,
	0xab, 0xc4, 0x21, 0x3f, 0xfb, 0x45, 0x30, 0x99, 0x29, 0xa7, 0x12, 0xf1, 0xe3, 0xf2, 0xf3, 0x92,
	0x37, 0x80, 0xf5, 0x17, 0xbc, 0x67, 0x59, 0xcb, 0x51, 0x78, 0x1a, 0xfc, 0x36, 0x4e, 0x95, 0xa3,
	0x04, 0x21, 0xb8, 0x61, 0x84, 0x5c, 0xa9, 0x42, 0x10, 0x1c, 0x46, 0xe3, 0x44, 0x76, 0x58, 0x1c,
	0x19, 0x43, 0x8e, 0x65, 0xc8, 0xfb, 0xb7, 0x03, 0x60, 0xac, 0xb8, 0xc7, 0xd0, 0x0b, 0xe3, 0x3e,
	0x6f, 0x10, 0xe1, 0x80, 0x11, 0x20, 0xf5, 0x53, 0x86, 0xe9, 0x93, 0x85, 0x17, 0x4c, 0xde, 0x21,
	0x76, 0xe4, 0xb9, 0xe7, 0x36, 0xe7, 0xef, 0x22, 0x45, 0x0b, 0x05, 0x72, 0xf9, 0x6a, 0x99, 0xfb,
	0x2b, 0xd8, 0x36, 0x4a, 0x87, 0x96, 0xbe, 0xf2, 0x8d, 0xfa, 0xee, 0x6b, 0x7d, 0x43, 0xa3, 0xeb,
	0xe7, 0x80, 0xec, 0x3e, 0xf6, 0x98, 0x59, 0x41, 0x53, 0xe5, 0x46, 0x4d, 0x9b, 0x61, 0xfc, 0x56,
	0xac, 0x30, 0x7a, 0xde, 0xc2, 0x03, 0xeb, 0xa0, 0xbc, 0xec, 0x2d, 0x6d, 0xce, 0x8d, 0xda, 0x76,
	0xf4, 0xbe, 0x38, 0x30, 0x18, 0x95, 0x5f, 0x00, 0xce, 0xf4, 0x2f, 0x83, 0x30, 0x9f, 0xd7, 0x57,
	0xbd, 0xed, 0x9c, 0x5f, 0xe1, 0xa2, 0xa2, 0x32, 0x3a, 0xe7, 0x94, 0xa5, 0xa3, 0xc2, 0x39, 0x6b,
	0xb7, 0x9d, 0xf3, 0x50, 0xac, 0x30, 0x7a, 0x5e, 0x00, 0x32, 0xe7, 0xf7, 0xb3, 0x76, 0xa3, 0x96,
	0xf5, 0x30, 0x2e, 0xee, 0xe5, 0x00, 0x36, 0x33, 0x36, 0xc8, 0xb1, 0xa3, 0x58, 0x3a, 0xea, 0x37,
	0xea, 0xd8, 0x90, 0x0b, 0xb4, 0x12, 0xef, 0x3d, 0xb4, 0x7e, 0x39, 0x1b, 0xb1, 0x7c, 0x72, 0xa6,
	0x6b, 0xfe, 0xeb, 0x86, 0x99, 0xff, 0x22, 0xcc, 0x1c, 0x8c, 0xd2, 0x78, 0x96, 0x14, 0x50, 0x9b,
	0x6a, 0x78, 0x01, 0xb5, 0x85, 0x8c, 0x40, 0x6d, 0x92, 0xfe, 0x0c, 0x5a, 0x74, 0x61, 0x92, 0x0b,
	0x08, 0x85, 0xdc, 0xc5, 0xa2, 0x57, 0x17, 0x34, 0x5a, 0xb6, 0x2f, 0x2f, 0x9f, 0x72, 0x55, 0x11,
	0x8d, 0x8c, 0x9b, 0xf0, 0xeb, 0xc3, 0x54, 0xdd, 0x6b, 0x68, 0x8f, 0xc9, 0x37, 0x72, 0x15, 0x25,
	0xe0, 0x37, 0xd5, 0xe6, 0xcc, 0x19, 0xf6, 0x6c, 0x1f, 0x92, 0xab, 0x5b, 0x63, 0xdb, 0xad, 0x3f,
	0x00, 0xe0, 0x9f, 0x17, 0x7d, 0x05, 0x54, 0xf6, 0x4b, 0x9f, 0xee, 0x10, 0xf8, 0x2d, 0xa3, 0x86,
	0xbd, 0x13, 0xd8, 0x5c, 0xd0, 0xb9, 0x04, 0xa6, 0xbe, 0x63, 0xc3, 0x54, 0x73, 0xff, 0xbe, 0x54,
	0x69, 0x2f, 0xb5, 0xb1, 0xeb, 0xaf, 0x25, 0xfa, 0x1a, 0xd1, 0x4f, 0x2e, 0xee, 0x73, 0x68, 0x47,
	0x74, 0xf9, 0xd2, 0x01, 0xa8, 0x58, 0x8a, 0xec, 0x8b, 0x99, 0xdf, 0x8a, 0xec, 0x6b, 0x1a, 0x06,
	0x62, 0x20, 0x3c, 0xb0, 0x34, 0x10, 0x96, 0x73, 0xfc, 0xe6, 0xc0, 0x8a, 0x76, 0xe1, 0x32, 0x58,
	0x99, 0xbf, 0x0c, 0xca, 0x47, 0x83, 0x55, 0xaf, 0x8f, 0xfb, 0x7f, 0xae, 0x41, 0xe5, 0xf3, 0xa3,
	0xd7, 0xae, 0x0f, 0xeb, 0x73, 0x6f, 0xaa, 0xae, 0xc2, 0xfd, 0xe5, 0xef, 0xcd, 0xbd, 0x47, 0xab,
	0xa6, 0xe5, 0x55, 0xf9, 0x1e, 0xd7, 0x39, 0x77, 0x8f, 0xd6, 0x3a, 0x97, 0x7f, 0x53, 0x69, 0x9d,
	0xab, 0xae, 0xdf, 0xf7, 0xdc, 0x1f, 0x41, 0x8d, 0x5e, 0x59, 0xdd, 0x2d, 0x29, 0x5b, 0x78, 0xbf,
	0xed, 0x6d, 0xcf, 0x71, 0xf5, 0xc2, 0x37, 0xd0, 0x2e, 0x3c, 0xa9, 0xbb, 0x1f, 0x14, 0x6c, 0x15,
	0x1f, 0x69, 0x7b, 0x1f, 0x2e, 0x9f, 0xd4, 0xda, 0x0e, 0x00, 0xcc, 0x73, 0x9b, 0xdb, 0x95, 0xd2,
	0x0b, 0x8f, 0xbd, 0xbd, 0x07, 0x4b, 0x66, 0xb4, 0x92, 0x53, 0xd8, 0x98, 0x7f, 0x3f, 0x73, 0xe7,
	0xbc, 0x3a, 0xff, 0xc6, 0xd5, 0xfb, 0x68, 0xe5, 0xbc, 0xad, 0x76, 0xfe, 0xed, 0x4c, 0xab, 0x5d,
	0xf1, 0x26, 0xa7, 0xd5, 0xae, 0x7c, 0x74, 0xbb, 0xe7, 0xfe, 0x1a, 0x3a, 0xc5, 0xd7, 0x2c, 0x57,
	0x39, 0x69, 0xe9, 0x6b, 0x5c, 0xef, 0xe1, 0x8a, 0x59, 0xad, 0xf0, 0x53, 0xa8, 0xd2, 0x33, 0x95,
	0xaa, 0x0d, 0xfb, 0x75, 0xab, 0xb7, 0x55, 0x64, 0xea, 0x55, 0x4f, 0xa1, 0x46, 0x5f, 0x60, 0x3a,
	0x01, 0x0a, 0x1f, 0x64, 0xbd, 0x96, 0xcd, 0xf5, 0xee, 0x3d, 0x2d, 0x29, 0x3b, 0x59, 0xc1, 0x4e,
	0xb6, 0xcc, 0x8e, 0x15, 0x9c, 0xb3, 0x9a, 0xf8, 0x67, 0xe8, 0xd9, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xd3, 0x97, 0x1d, 0xe4, 0x26, 0x1a, 0x00, 0x00,
}
